# Generated by Django 3.2.5 on 2021-07-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('found_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type_choices', models.CharField(choices=[('UNIVERSALL', 'UNIVERSALL'), ('KIDS', 'KIDS'), ('MAN', 'MAN'), ('WOMEN', 'WOMEN')], default='UNIVERSALL', max_length=11)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('brand_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.company')),
            ],
        ),
    ]
